### ISSUE TITLE
Upload Pictures

### ISSUE THREAD

**Issue by DocMolle** [DocMolle/Vaadin-BOVISLabor#1]
As a user you should be able to upload media and view the post you submitted

**Comment by hendrikstill** [comment]
See branch UploadPicturesAndThumbnails

**Comment by theWalli** [comment]
Error when uploading for the first time in a session:

Okt 20, 2015 8:32:21 PM com.vaadin.server.DefaultErrorHandler doDefault
Schwerwiegend: 
com.vaadin.server.UploadException: Upload failed
	at com.vaadin.server.communication.FileUploadHandler.streamToReceiver(FileUploadHandler.java:624)
	at com.vaadin.server.communication.FileUploadHandler.handleFileUploadValidationAndData(FileUploadHandler.java:453)
	at com.vaadin.server.communication.FileUploadHandler.doHandleSimpleMultipartFileUpload(FileUploadHandler.java:403)
	at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:285)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1408)
	at com.vaadin.cdi.internal.VaadinCDIServletService.handleRequest(VaadinCDIServletService.java:82)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:351)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.vaadin.server.NoOutputStreamException
	at com.vaadin.server.communication.FileUploadHandler.streamToReceiver(FileUploadHandler.java:552)
	... 28 more

**Comment by theWalli** [comment]
Not important right now...
