### ISSUE TITLE
Export statistics

### ISSUE THREAD

**Issue by DocMolle** [DocMolle/Vaadin-BOVISLabor#9]
As a logged in admin you should be able to export a diagram with the users who uploaded the most pictures

**Comment by DocMolle** [comment]
Statistics is implemented (see branch export_statistics). It is not really an export, but more of a view to see some stats. Should be fine.

**Comment by theWalli** [comment]
Broken as hell:

Okt 20, 2015 8:46:36 PM com.vaadin.server.DefaultErrorHandler doDefault
Schwerwiegend: 
java.lang.NullPointerException
	at com.bovis.view.StatisticsForm.showStatisticsForUser(StatisticsForm.java:38)
	at com.bovis.view.AdminPanelWindow$1.select(AdminPanelWindow.java:50)
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1003)
	at com.vaadin.ui.Grid.fireSelectionEvent(Grid.java:4894)
	at com.vaadin.ui.Grid$AbstractSelectionModel.fireSelectionEvent(Grid.java:948)
	at com.vaadin.ui.Grid$SingleSelectionModel.deselectInternal(Grid.java:990)
	at com.vaadin.ui.Grid$SingleSelectionModel.deselect(Grid.java:983)
	at com.vaadin.ui.Grid$SingleSelectionModel.select(Grid.java:960)
	at com.vaadin.ui.Grid$3.select(Grid.java:3701)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:313)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:202)
	at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:153)
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:232)
	at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:492)
	at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:88)
	at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:78)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:199)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:107)
	at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:154)
	at org.atmosphere.container.Tomcat7Servlet30SupportWithWebSocket.service(Tomcat7Servlet30SupportWithWebSocket.java:62)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:571)
	at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:333)
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:328)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:425)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatchReader(DefaultWebSocketProcessor.java:795)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:527)
	at org.atmosphere.container.TomcatWebSocketHandler.onTextData(TomcatWebSocketHandler.java:104)
	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:191)
	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:139)
	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:616)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by DocMolle** [comment]
Das Vaadin charts add-on macht derbe Probleme. Irgendwas mit GWT, bitte mal branch charts_and_graphs angucken testen. John Doe einloggen und Statistik angucken drücken. Diese Meldung kommt immer...

**Comment by DocMolle** [comment]
Ich werde nun einfach eine Tabelle mit den 5 Usern machen, die die meisten Posts haben. Dafür sollte aber Issue #28 gefixed werden. :cat:
